env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
overrides:
  - files:
      - "*.svelte"
    parser: svelte-eslint-parser
    parserOptions:
      parser:
        ts: "@typescript-eslint/parser"
        typescript: "@typescript-eslint/parser"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
  - svelte
  - prettier
rules:
  prettier/prettier: error
